project_id = "mlzgeceiinjwpffgsxuy"

[functions.pdf-processing-orchestrator]
verify_jwt = true

[functions.pdf-text-extractor]
verify_jwt = true

[functions.ai-data-organizer]
verify_jwt = true

[functions.proposal-formatter]
verify_jwt = true

[functions.data-validator]
verify_jwt = true

[functions.data-saver]
verify_jwt = true

[functions.get-adobe-credentials]
verify_jwt = true

[functions.process-energy-bill]
verify_jwt = true

[functions.whapi-send-message]
verify_jwt = true

[functions.test-resend-email]
verify_jwt = true

[functions.whapi-webhook]
verify_jwt = true

[functions.ai-proposal-assistant]
verify_jwt = true

[functions.ai-sentiment-analysis]
verify_jwt = true

[functions.ai-dynamic-pricing]
verify_jwt = true

[functions.ai-fraud-detection]
verify_jwt = true

[functions.ai-chatbot]
verify_jwt = true

[functions.pdf-processing-logger]
verify_jwt = true

[functions.extract-pdf-data]
verify_jwt = true

[functions.upload-to-adobe]
verify_jwt = true

[functions.process-adobe-extraction]
verify_jwt = true

[functions.adobe-logger]
verify_jwt = true

[functions.debug-adobe-health]
verify_jwt = true

[functions.system-monitor]
verify_jwt = true