// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlzgeceiinjwpffgsxuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1semdlY2VpaW5qd3BmZmdzeHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjkwMDEsImV4cCI6MjA2NjAwNTAwMX0.M7EkRznCinwtA8SExnF143iVsEUO7uUNgNyZ_brzprQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);